# -----------------------------------------------------------
# Schema and Base Configuration
# -----------------------------------------------------------

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = "catppuccin_mocha"
command_timeout = 1000

# -----------------------------------------------------------
# Primary Prompt Format
# -----------------------------------------------------------

format = """
[░▒▓](fg:ckyellow100)\
[ $os](bg:ckyellow100 fg:ckbrown100)\
[](bg:ckyellow200 fg:ckyellow100)\
$directory\
[](fg:ckyellow200 bg:ckyellow300)\
$git_branch\
$git_status\
[](fg:ckyellow300 bg:ckbrown100)\
$php\
$custom\
[](fg:ckbrown100 bg:termbg)\
$character\
$cmd_duration\
"""

# -----------------------------------------------------------
# Directory Configuration
# -----------------------------------------------------------

[directory]
style = "fg:ckbrown100 bg:ckyellow200"
format = "[ $path]($style)"
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"~/Developer/ck" = "ck"
"~/Developer/dotfiles" = " dotfiles"
"~/Developer/ck/infrastructure" = " infrastructure"
"~/Developer/infrastructure" = " infrastructure"
"~/Developer/pinktum/academy/" = "academy-"

# -----------------------------------------------------------
# Git Configuration
# -----------------------------------------------------------

[git_branch]
symbol = ""
style = "bg:ckyellow300"
format = '[[ $symbol $branch ](fg:ckbrown100 bg:ckyellow300)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:ckbrown100 bg:ckyellow300)]($style)'

[git_commit]
tag_disabled = true

# -----------------------------------------------------------
# Language & Tool Configuration
# -----------------------------------------------------------

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:ckyellow100 bg:ckbrown100)]($style)'

[kubernetes]
symbol = "⎈ "
format = " [$symbol$context( \\($namespace\\))]($style) "
style = "bright-blue"
disabled = false

[custom.nuxtjs]
symbol = ""
format = '[ $symbol ](fg:ckyellow100 bg:ckbrown100)($style)'
style = "bg:#212736"
detect_files = ["nuxt.config.ts", "nuxt.config.js", "nuxt.config.mjs"]

# [custom.docker]
# symbol = "󰡨 "
# style = "fg:ckyellow100 bg:ckbrown100"
# format = "[ $symbol ]($style)"
# detect_files = ["Dockerfile", "docker-compose.yaml", "docker-compose.yml", "compose.yaml", "compose.yml"]
# when = """ command -v docker &>/dev/null ; exit (echo $?) ; """

# -----------------------------------------------------------
# System Information
# -----------------------------------------------------------

[os]
format = "$symbol "
disabled = false
style = "bold"

[os.symbols]
Macos = ""
Linux = ""
Ubuntu = ""
Windows = ""
Debian = ""

[hostname]
format = "$hostname"
ssh_only = false

[hostname.aliases]
"Neos-Work-MacBook-Pro" = "ck"
"Neos-MacBook-Pro" = "ck"
"Neos-Work-MBP" = "ck"
"Neos-MBP" = "ck"
"Mac" = "ck"
"MacBook-Pro" = "ck"


# -----------------------------------------------------------
# Prompt Configuration
# -----------------------------------------------------------

[character]
success_symbol = '[ ➜](bold ckyellow300)'
error_symbol = '[ ✗](bold red)'

# -----------------------------------------------------------
# Palette
# -----------------------------------------------------------

[palettes.catppuccin_mocha]

# Custom CK Colors
ckyellow100 = "#f6d277"
ckyellow200 = "#EBBE55"
ckyellow300 = "#DFAE3B"
ckyellow400 = "#DCAB38"
ckbrown100 = "#2d2b27"
termbg = "#131c2b"

# Catppuccin Mocha Colors
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
