# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# A minimal left prompt
palette = "catppuccin_mocha"
command_timeout = 1000

# CK: p10k
# ============================================================================
format = """\
[](bg:termbg fg:ckyellow100)\
[$os$hostname ](bold bg:ckyellow100 fg:ckblack100)\
$git_branch\
$git_status\
$git_metrics\
$directory\
[](fg:ckyellow300 bg:termbg)\
$character\
$cmd_duration\
"""

[os]
format = "$symbol "
disabled = false
style = "bold"

[os.symbols]
Macos = ""
Linux = ""
Ubuntu = ""
Windows = ""
Debian = ""

[hostname]
# format = " $hostname"
format = "$hostname"
ssh_only = false

[hostname.aliases]
"Neos-Work-MacBook-Pro" = "ck"
"Neos-MacBook-Pro" = "ck"
"Neos-Work-MBP" = "ck"
"Neos-MBP" = "ck"
"Mac" = "ck"
"MacBook-Pro" = "ck"

[directory]
format = "[ $path ]($style)"
style = "bold fg:ckblack100 bg:ckyellow300"
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'

[directory.substitutions]
"~/Developer/dotfiles" = " dotfiles"
"~/Developer/ck/infrastructure" = " infrastructure"
"~/Developer/infrastructure" = " infrastructure"
"~/Developer/ck" = "ck"
"~/Developer/pinktum/academy/" = "academy-"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:ckblack100 bg:ckyellow200"

[git_status]
format = '[$all_status]($style)'
style = "fg:ckblack100 bg:ckyellow200"

[git_metrics]
format = "([+$added ]($added_style))[ ]($added_style)"
added_style = "fg:ckblack100 bg:ckyellow200"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

# ============================================================================
# End of CK: p10k



# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ ➜](bold ckyellow300)'
error_symbol = '[ ✗](bold red)'

[golang]
format = '[ ](bold cyan)'

[git_commit]
tag_disabled = true

[nodejs]
format = '[$symbol($version )]($style)'

[package]
disabled = true

[kubernetes]
symbol = "⎈ "
format = " [$symbol$context( \\($namespace\\))]($style) "
style = "bright-blue"
disabled = false

[php]
symbol =  " "
format = '[ $symbol](bold $style)'
style = "bold fg:ckblack100 bg:ckyellow300"

[custom.docker]
# command = "echo 󰡨 "
symbol = "󰡨 "
style = "bold fg:ckblack100 bg:ckyellow300"
format = "[ $symbol]($style)"
detect_files = ["Dockerfile", "docker-compose.yaml", "docker-compose.yml", "compose.yaml", "compose.yml"]
when = """ command -v docker &>/dev/null ; exit (echo $?) ; """

# Palette
[palettes.catppuccin_mocha]
ckyellow100 = "#f6d277"
ckyellow200 = "#EBBE55"
ckyellow300 = "#DAAD42"
ckyellow400 = "#DCAB38"
ckblack100 = "#2d2b27"

termbg = "#1a1b26"

rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
