# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# A minimal left prompt
palette = "catppuccin_mocha"
command_timeout = 1000

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[golang]
format = '[ ](bold cyan)'

[git_branch]
format = '[$symbol$branch](bold pink)'

[git_commit]
tag_disabled = true

[nodejs]
format = '[$symbol($version )]($style)'

[package]
disabled = true

[php]
format = '[ ](bold blue)'

[custom.docker]
# command = "echo 󰡨 "
symbol = "󰡨 "
format = "[$symbol](bold blue)"
detect_files = ["Dockerfile", "docker-compose.yaml", "docker-compose.yml", "compose.yaml", "compose.yml"]
when = """ command -v docker &>/dev/null ; exit (echo $?) ; """

# Increase truncation length and add truncation symbol
[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = '…/'

[directory.substitutions]
"~/Developer/" = "󱃖 "
"~/Developer" = "󱃖 "
"~/" = "󰋜 "
"~" = "󰋜 "
"pinktum/academy/" = "academy-"

# Palette
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
