vars: {}
cmds: {}

bookmarks:
  # Global
  - name: "Reload Sketchybar"
    cmds: ["sketchybar --reload"]
    exec: true
    labels: ["sketchybar"]

  # PINKTUM Academy
  - name: "Redeploy Academy Backend (DEV)"
    cmds: ["kubectl rollout restart deploy/backend -n academy-dev"]
    labels: ["kubernetes", "rollout", "dev", "academy"]
    paths: ["/Users/neo/Developer/pinktum"]
  - name: "Redeploy Academy Backend (QA)"
    cmds: ["kubectl rollout restart deploy/backend -n academy-qa"]
    labels: ["kubernetes", "rollout", "qa", "academy"]
    paths: ["/Users/neo/Developer/pinktum"]
  - name: "Redeploy Academy Backend (PO)"
    cmds: ["kubectl rollout restart deploy/backend -n academy-po"]
    labels: ["kubernetes", "rollout", "po", "academy"]
    paths: ["/Users/neo/Developer/pinktum"]
  - name: "Redeploy Academy Backend (PROD)"
    cmds: ["kubectl rollout restart deploy/backend -n academy-prod"]
    labels: ["kubernetes", "rollout", "prod", "academy"]
    paths: ["/Users/neo/Developer/pinktum"]
